name: 'Notify branches out of sync'
description: 'hiho'
inputs:
  from_branch:
    required: true
  to_branch:
    required: true
  delta:
    required: true
    description: >
      Number of seconds we should ignore out of sync issues for
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run a multi-line script
      run: |
        git branch --list
        git log --no-merges --oneline origin/${{ inputs.from_branch }} ^origin/${{ inputs.to_branch }}
        OUTPUT=$(git log --no-merges --oneline origin/${{ inputs.frombranch }} ^origin/{{ inputs.to_branch }})
        echo $OUTPUT
